### ISSUE TITLE
Reducers should not be generating timestamps

### ISSUE THREAD

**Issue by markerikson** [praghus/posthumus#1]
Hi.  First off, this is really neat-looking!  Played around with the game for a few minutes, and it plays pretty nice so far.  

Looking at the reducers, it looks like they're generating timestamps:

```js
const actionsMap = {
    [TICKER_STARTED]: (state) => {
        return Object.assign({}, state, {
            tickerStarted: true,
            lastFrameTime: performance.now()
        })
    },
    [TIME_TICK]: (state) => {
        return Object.assign({}, state, {
            lastFrameTime: performance.now()
        })
    }
}
```

While that will technically work, it's not how reducers _should_ behave.  Ideally, all randomness should be kept outside of reducers so that they're "pure" and return the exact same values for the same state+action inputs.

I'd suggest moving the `performance.now()` calls into the action creation side instead.

For more info, see [Roll the Dice: Random Numbers in Redux](https://daveceddia.com/random-numbers-in-redux/) and [Random in Redux](https://blog.ohlman.io/random-in-redux-b6b9932ad061).

**Comment by praghus** [comment]
Hi.
Generally speaking, you are right.  It was just a prove of concept when I was experimenting at the beginning. However, it did its job, so I left it that way. 
But if somebody has already noticed it, I think that it's worth changing.

Thanks.
